General:
    TOKEN: ""
    STATUS: "online"

    ACTIVITY: "watching"
    DOING_ACTIVITY: "AI"
    STREAMING_ACTIVITY_TWITCH_URL: ""

    EMBED_COLOR: "#65A8E6"

API:
    GROQ_API_KEY: ""

Staff:
    STAFF_ROLES: []